[package]
name = "webgate-browser"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
webgate-core = { version = "0.1.0", path = "../webgate-core" }

[dev-dependencies]
webgate-transport = { version = "0.1.0", path = "../webgate-transport" }

[lints]
workspace = true
