[package]
name = "webgate-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
webgate-browser = { version = "0.1.0", path = "../webgate-browser" }
webgate-core = { version = "0.1.0", path = "../webgate-core" }
webgate-platform = { version = "0.1.0", path = "../webgate-platform" }
webgate-transport = { version = "0.1.0", path = "../webgate-transport" }

[lints]
workspace = true
